networks:
  agronetwork:
    name: agronetwork
    driver: bridge


services:
  minio:
    image: minio/minio:RELEASE.2024-02-14T21-36-02Z
    container_name: minio
    env_file:
      - ../.env
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-api-data:/minio
    networks:
      - agronetwork

  minio_init:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - agronetwork
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/agro-photos;
      /usr/bin/mc policy set public myminio/agro-photos;
      exit 0;
      "

volumes:
  minio-api-data:
