networks:
  agronetwork:
    name: agronetwork
    driver: bridge

services:
  agro-mongo:
    image: mongo:latest
    container_name: agro-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: files
    ports:
      - "27017:27017"
    volumes:
      - agro-mongo:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - agronetwork

volumes:
  agro-mongo: